FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git curl tar && \
  curl -sSL "https://github.com/cli/cli/releases/download/v2.47.0/gh_2.47.0_linux_amd64.tar.gz" | tar xz -C /tmp && \
  mv /tmp/gh_2.47.0_linux_amd64/bin/gh /usr/local/bin/ && \
  rm -rf /tmp/gh_* && \
  git config --global --add safe.directory /app

COPY package.json ./
RUN npm install

COPY . .
EXPOSE 5173

CMD ["npm", "run", "dev"]
