import { screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { TransactionsPage } from '@/Controller/TransactionsPage'
import type { EntityManager } from '@/Repository/EntityManager'
import { createTestEm, FakeTabs, renderRoute } from '../helpers/workbookTestBed'

const mocks = vi.hoisted(() => ({
  em: null as unknown as EntityManager,
  toast: { success: vi.fn(), error: vi.fn() },
}))
vi.mock('@/Hook/useEntityManager', () => ({ useEntityManager: () => mocks.em }))
vi.mock('@/Component/Toast', () => ({ toast: mocks.toast }))

let tabs: FakeTabs

function seedWorkbook(): FakeTabs {
  const seeded = new FakeTabs()
  seeded.seed('clients', { id: 'CL1', name: 'TechStart Solutions' })
  seeded.seed('jobs', {
    id: 'J1',
    client_id: 'CL1',
    description: 'Prototype batch',
  })
  seeded.seed('inventory', { id: 'INV1', type: 'filament', name: 'PLA White' })
  // Income generated by paying job J1.
  seeded.seed('transactions', {
    id: 'T1',
    date: '2026-02-01',
    type: 'income',
    amount: '120',
    category: 'job',
    concept: 'Prototype batch paid',
    ref_type: 'job',
    ref_id: 'J1',
    client_id: 'CL1',
  })
  // Expense that bought stock.
  seeded.seed('transactions', {
    id: 'T11',
    date: '2026-01-15',
    type: 'expense',
    amount: '-29.99',
    category: 'filament',
    concept: 'PLA White',
  })
  seeded.seed('lots', {
    id: 'L1',
    inventory_id: 'INV1',
    transaction_id: 'T11',
    quantity: '1000',
    amount: '29.99',
  })
  // Overhead expense with no lots.
  seeded.seed('transactions', {
    id: 'T12',
    date: '2026-01-20',
    type: 'expense',
    amount: '-10',
    category: 'electric',
    concept: 'January power',
  })
  seeded.seed('transactions', {
    id: 'T13',
    date: '2026-01-21',
    type: 'expense',
    amount: '-5',
    concept: 'Archived',
    archived: 'true',
  })
  return seeded
}

function bodyRows(): HTMLElement[] {
  return within(screen.getByRole('table')).getAllByRole('row').slice(1)
}

function rowIds(): string[] {
  return bodyRows().map(
    (row) => within(row).getAllByRole('cell')[0].textContent ?? ''
  )
}

describe('TransactionsPage', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    tabs = seedWorkbook()
    mocks.em = createTestEm(tabs)
  })

  it('lists only active transactions', () => {
    renderRoute(<TransactionsPage />)

    expect(rowIds().sort()).toEqual(['T1', 'T11', 'T12'])
    expect(screen.queryByText('Archived')).not.toBeInTheDocument()
  })

  it('sums the balance across income and expense', () => {
    renderRoute(<TransactionsPage />)

    // 120 - 29.99 - 10
    expect(screen.getByText(/^Balance:/)).toHaveTextContent('Balance: €80.01')
  })

  it('is read-only: no edit or delete controls', () => {
    renderRoute(<TransactionsPage />)

    expect(
      screen.queryByRole('button', { name: /edit/i })
    ).not.toBeInTheDocument()
    expect(
      screen.queryByRole('button', { name: /delete|remove/i })
    ).not.toBeInTheDocument()
  })

  describe('id column', () => {
    it('links an expense id to its detail page', () => {
      renderRoute(<TransactionsPage />)

      expect(
        screen.getByTestId('transaction-expense-detail-link-T11')
      ).toHaveAttribute('href', '/transactions/T11')
    })

    it('leaves an income id as plain text, because income has no detail page', () => {
      renderRoute(<TransactionsPage />)

      expect(
        screen.queryByTestId('transaction-expense-detail-link-T1')
      ).not.toBeInTheDocument()
      expect(screen.getByText('T1')).toBeInTheDocument()
    })
  })

  describe('amount column', () => {
    it('paints income green and expense red', () => {
      renderRoute(<TransactionsPage />)

      const amountOf = (id: string) =>
        within(
          bodyRows().find(
            (row) => within(row).queryByText(id) !== null
          ) as HTMLElement
        )
          .getAllByRole('cell')[3]
          .querySelector('span')

      expect(amountOf('T1')).toHaveClass('text-success')
      expect(amountOf('T1')).toHaveTextContent('€120.00')
      expect(amountOf('T11')).toHaveClass('text-danger')
      expect(amountOf('T11')).toHaveTextContent('-€29.99')
    })

    it('keeps a zero-value expense red rather than neutral', () => {
      tabs = new FakeTabs()
      tabs.seed('transactions', {
        id: 'T20',
        date: '2026-03-01',
        type: 'expense',
        amount: '0',
        concept: 'Free sample',
      })
      mocks.em = createTestEm(tabs)
      renderRoute(<TransactionsPage />)

      expect(bodyRows()[0].querySelectorAll('span')[0]).toHaveClass(
        'text-danger'
      )
    })
  })

  describe('concept link rules', () => {
    it('links a job-backed transaction to its job', () => {
      renderRoute(<TransactionsPage />)

      expect(
        screen.getByTestId('transaction-concept-job-link-T1')
      ).toHaveAttribute('href', '/jobs/J1')
    })

    it('links an expense that bought stock to its expense detail', () => {
      renderRoute(<TransactionsPage />)

      const link = screen.getByTestId(
        'transaction-concept-expense-detail-link-T11'
      )
      expect(link).toHaveTextContent('PLA White')
      expect(link).toHaveAttribute('href', '/transactions/T11')
    })

    it('leaves an overhead expense concept unlinked', () => {
      renderRoute(<TransactionsPage />)

      expect(
        screen.queryByTestId('transaction-concept-expense-detail-link-T12')
      ).not.toBeInTheDocument()
      expect(screen.getByText('January power')).toBeInTheDocument()
    })

    it('leaves an expense unlinked once its only lot is archived', () => {
      tabs = new FakeTabs()
      tabs.seed('transactions', {
        id: 'T11',
        date: '2026-01-15',
        type: 'expense',
        amount: '-29.99',
        concept: 'PLA White',
      })
      tabs.seed('lots', {
        id: 'L1',
        inventory_id: 'INV1',
        transaction_id: 'T11',
        quantity: '1000',
        amount: '29.99',
        archived: 'true',
      })
      mocks.em = createTestEm(tabs)
      renderRoute(<TransactionsPage />)

      expect(
        screen.queryByTestId('transaction-concept-expense-detail-link-T11')
      ).not.toBeInTheDocument()
    })
  })

  describe('client column', () => {
    it('links a client', () => {
      renderRoute(<TransactionsPage />)

      const link = screen.getByTestId('transaction-client-link-T1')
      expect(link).toHaveTextContent('TechStart Solutions')
      expect(link).toHaveAttribute('href', '/clients/CL1')
    })

    it('shows nothing for a transaction with no client', () => {
      renderRoute(<TransactionsPage />)

      expect(
        screen.queryByTestId('transaction-client-link-T11')
      ).not.toBeInTheDocument()
    })

    it('shows nothing when the client no longer resolves', () => {
      tabs = new FakeTabs()
      tabs.seed('transactions', {
        id: 'T1',
        date: '2026-02-01',
        type: 'income',
        amount: '120',
        concept: 'Paid',
        client_id: 'CL404',
      })
      mocks.em = createTestEm(tabs)
      renderRoute(<TransactionsPage />)

      expect(
        screen.queryByTestId('transaction-client-link-T1')
      ).not.toBeInTheDocument()
    })
  })

  describe('sorting', () => {
    it('sorts newest first by default and reverses on toggle', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      expect(rowIds()).toEqual(['T1', 'T12', 'T11'])

      await user.click(
        screen.getByRole('button', { name: /date, sorted descending/i })
      )
      expect(rowIds()).toEqual(['T11', 'T12', 'T1'])
    })

    it('sorts by every other column', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      await user.click(screen.getByRole('button', { name: /sort by id/i }))
      expect(rowIds()).toEqual(['T1', 'T11', 'T12'])

      await user.click(screen.getByRole('button', { name: /sort by amount/i }))
      expect(rowIds()).toEqual(['T11', 'T12', 'T1'])

      await user.click(screen.getByRole('button', { name: /sort by type/i }))
      expect(rowIds()[0]).toBe('T11')

      await user.click(
        screen.getByRole('button', { name: /sort by category/i })
      )
      expect(rowIds()[0]).toBe('T12')

      await user.click(screen.getByRole('button', { name: /sort by concept/i }))
      expect(rowIds()[0]).toBe('T12')

      // Rows with no client have nothing to rank on, so they sink to the bottom.
      await user.click(screen.getByRole('button', { name: /sort by client/i }))
      expect(rowIds()).toEqual(['T1', 'T11', 'T12'])
    })

    it('shows and ranks a transaction with no stored amount as zero', async () => {
      const user = userEvent.setup()
      tabs.seed('transactions', {
        id: 'T14',
        date: '2026-01-22',
        type: 'expense',
        category: 'other',
        concept: 'Amount pending',
      })
      mocks.em = createTestEm(tabs)
      renderRoute(<TransactionsPage />)

      const row = bodyRows().find(
        (candidate) => within(candidate).queryByText('T14') !== null
      ) as HTMLElement
      expect(within(row).getByText('€0.00')).toBeInTheDocument()

      await user.click(screen.getByRole('button', { name: /sort by amount/i }))
      expect(rowIds()).toEqual(['T11', 'T12', 'T14', 'T1'])
    })
  })

  describe('search', () => {
    it('filters fuzzily', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      await user.type(screen.getByRole('searchbox'), 'power')

      expect(rowIds()).toEqual(['T12'])
    })

    it('reports no matches rather than an empty ledger', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      await user.type(screen.getByRole('searchbox'), 'zzzznothing')

      expect(screen.getByText('No rows match your search.')).toBeInTheDocument()
    })
  })

  it('shows the empty state when there are no transactions', () => {
    mocks.em = createTestEm(new FakeTabs())
    renderRoute(<TransactionsPage />)

    expect(screen.getByText(/No transactions yet/)).toBeInTheDocument()
    expect(screen.getByText(/^Balance:/)).toHaveTextContent('Balance: €0.00')
  })

  describe('record purchase', () => {
    it('opens the dialog and closes it again', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      await user.click(screen.getByTestId('transactions-record-purchase'))
      expect(screen.getByTestId('purchase-dialog')).toBeInTheDocument()

      await user.click(screen.getByRole('button', { name: 'Cancel' }))
      expect(screen.queryByTestId('purchase-dialog')).not.toBeInTheDocument()
    })

    it('navigates to the new expense once a purchase is recorded', async () => {
      const user = userEvent.setup()
      renderRoute(<TransactionsPage />)

      await user.click(screen.getByTestId('transactions-record-purchase'))
      await user.type(screen.getByLabelText('Amount'), '12')
      await user.type(screen.getByLabelText('Notes'), 'New spool')
      await user.click(screen.getByTestId('purchase-submit'))

      expect(screen.getByTestId('location')).toHaveTextContent(
        '/transactions/T14'
      )
      expect(screen.queryByTestId('purchase-dialog')).not.toBeInTheDocument()
    })
  })
})
